create extension if not exists vector with schema extensions;
create table if not exists meetings(id uuid primary key default gen_random_uuid(),user_id uuid default auth.uid(),title text not null,client text,project text,started_at timestamptz default now(),consent_confirmed boolean not null default false,created_at timestamptz default now());
create table if not exists transcript_segments(id uuid primary key default gen_random_uuid(),meeting_id uuid references meetings(id) on delete cascade,speaker text not null,start_ms integer not null,end_ms integer not null,text text not null,embedding extensions.vector(1536),created_at timestamptz default now());
create table if not exists meeting_insights(meeting_id uuid primary key references meetings(id) on delete cascade,summary text,decisions jsonb default '[]',risks jsonb default '[]',created_at timestamptz default now());
create table if not exists action_items(id uuid primary key default gen_random_uuid(),meeting_id uuid references meetings(id) on delete cascade,task text not null,owner text,due_date date,source_segment_ids uuid[] default '{}',review_status text not null default 'pending' check(review_status in('pending','approved','rejected')),created_at timestamptz default now());
create index if not exists transcript_embedding_hnsw on transcript_segments using hnsw (embedding extensions.vector_cosine_ops);
alter table meetings enable row level security;alter table transcript_segments enable row level security;alter table meeting_insights enable row level security;alter table action_items enable row level security;
create policy "owners read meetings" on meetings for select using(user_id=auth.uid());
create or replace function match_transcript_segments(query_embedding extensions.vector(1536),match_count int default 8,client_filter text default null) returns table(id uuid,meeting_id uuid,meeting_title text,start_ms int,end_ms int,text text,similarity float) language sql stable as $$ select s.id,s.meeting_id,m.title,s.start_ms,s.end_ms,s.text,1-(s.embedding<=>query_embedding) from transcript_segments s join meetings m on m.id=s.meeting_id where (client_filter is null or m.client=client_filter) order by s.embedding<=>query_embedding limit match_count; $$;
